### PR TITLE
fix: ternary operator highlighting error (issue #14)

### PR DESCRIPTION
**Pull request by tuoz**

### CODE REVIEW

**Comment by natewallace** [comment]
I think making the double quote(") end a ternary expression will cause other issues since a double quote could be part of a valid javascript/angular expression.  Take the following example:
```
<p>{{true === false ? "Hello" : "World"}}</p>
```

**Comment by tuoz** [comment]
I don't know how VSCode uses it, but it works well

**Comment by sfabriece** [comment]
this is a problem if it is used in a property binding

 ```html
<div [title]="true ? 'yes':'no'"></div>
```

**Comment by 0x054** [comment]
I could be wrong... But syntax seems to work fine if you wrap the ternary in parenthesis...

`<div [title]="(true ? 'yes': 'no')"></div>`

**Comment by sfabriece** [comment]
@IVIyg0t it probably works if it wrapped, but I shouldn't have to wrap it just to get the syntax highlighting to work. Plus if using tools like prettier, I might not have a choice.

**Pull request closed without merging**
